let resultado = true && false;
let resultado2 = true && true;
let resultad1o = false && false;
let resultado1 = false && true;
console.log("AND");
console.log("A" +"|B" + "|R");
console.log("1"+"|0"+"|" + "0" + "->"+resultado);
console.log("0"+"|1"+"|" + "0" + "->"+resultado1);
console.log("1"+"|1"+"|" + "1" + "->"+resultado2);
console.log("0"+"|0"+"|" + "0" + "->"+resultad1o);
console.log("OR");
console.log("A" +"|B" + "|R");
console.log("1"+"|0"+"|" + "1" + "->"+resultado);
console.log("0"+"|1"+"|" + "1" + "->"+resultado1);
console.log("1"+"|1"+"|" + "1" + "->"+resultado2);
console.log("0"+"|0"+"|" + "0" + "->"+resultad1o);
